server.port=8090
server.servlet.context-path=/api

spring.datasource.url=jdbc:mysql://localhost:3306/feedbackhub
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET:FeedbackHub2024SecretKeyForJWTMustBe32CharLong!}
app.jwt.expiration=86400000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB